# Generated by Django 5.0.4 on 2024-04-26 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creado',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 26, 16, 13, 58, 809437)),
        ),
        migrations.AddField(
            model_name='project',
            name='descripcion',
            field=models.TextField(default='dd'),
        ),
        migrations.AddField(
            model_name='project',
            name='tecnologia',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='titulo',
            field=models.CharField(default='titulo1', max_length=250),
        ),
    ]
